#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Clinic_Management_System
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ClinicManagementSystem_Group3")]
	public partial class ClinicDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ClinicDatabaseDataContext() : 
				base(global::Clinic_Management_System.Properties.Settings.Default.ClinicManagementSystem_Group3ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ClinicDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspAddMedicine")]
		public int uspAddMedicine([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrandName", DbType="NVarChar(100)")] string brandName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GenericName", DbType="NVarChar(MAX)")] string genericName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpirationDate", DbType="Date")] System.Nullable<System.DateTime> expirationDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Manufacturer", DbType="NVarChar(MAX)")] string manufacturer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quantity", DbType="Int")] System.Nullable<int> quantity)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), brandName, genericName, expirationDate, manufacturer, quantity);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspAddPatient")]
		public int uspAddPatient([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientFullName", DbType="NVarChar(100)")] string patientFullName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Age", DbType="Int")] System.Nullable<int> age, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="NVarChar(50)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientType", DbType="NVarChar(50)")] string patientType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientDesc", DbType="NVarChar(50)")] string patientDesc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ContactNumber", DbType="NChar(11)")] string contactNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EmailAddress", DbType="NVarChar(100)")] string emailAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(MAX)")] string address)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), patientFullName, age, gender, patientType, patientDesc, contactNumber, emailAddress, address);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspInsertLogs")]
		public int uspInsertLogs([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UID", DbType="Int")] System.Nullable<int> uID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LogDesc", DbType="NVarChar(MAX)")] string logDesc)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uID, logDesc);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspInsertMeds")]
		public int uspInsertMeds([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MedName", DbType="NVarChar(100)")] string medName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MedType", DbType="NVarChar(MAX)")] string medType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpDate", DbType="Date")] System.Nullable<System.DateTime> expDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Manufacturer", DbType="NVarChar(MAX)")] string manufacturer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Qty", DbType="Int")] System.Nullable<int> qty, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="NVarChar(50)")] string status)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), medName, medType, expDate, manufacturer, qty, status);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspInsertSupplies")]
		public int uspInsertSupplies([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SupplyName", DbType="NVarChar(100)")] string supplyName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpDate", DbType="Date")] System.Nullable<System.DateTime> expDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Supplier", DbType="NVarChar(100)")] string supplier, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Qty", DbType="Int")] System.Nullable<int> qty, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Status", DbType="NVarChar(50)")] string status, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UnitPrice", DbType="Money")] System.Nullable<decimal> unitPrice)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), supplyName, expDate, supplier, qty, status, unitPrice);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspLogin")]
		public ISingleResult<uspLoginResult> uspLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PW", DbType="NVarChar(50)")] string pW)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), email, pW);
			return ((ISingleResult<uspLoginResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectAllMedicine")]
		public ISingleResult<uspSelectAllMedicineResult> uspSelectAllMedicine()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspSelectAllMedicineResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectAllPatient")]
		public ISingleResult<uspSelectAllPatientResult> uspSelectAllPatient()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspSelectAllPatientResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectAllUser")]
		public ISingleResult<uspSelectAllUserResult> uspSelectAllUser()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspSelectAllUserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectMedicineByExpDate")]
		public ISingleResult<uspSelectMedicineByExpDateResult> uspSelectMedicineByExpDate([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpirationDate", DbType="Date")] System.Nullable<System.DateTime> expirationDate)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), expirationDate);
			return ((ISingleResult<uspSelectMedicineByExpDateResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectMedicineByManufacturer")]
		public ISingleResult<uspSelectMedicineByManufacturerResult> uspSelectMedicineByManufacturer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Manufacturer", DbType="NVarChar(MAX)")] string manufacturer)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manufacturer);
			return ((ISingleResult<uspSelectMedicineByManufacturerResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectPatientByAge")]
		public ISingleResult<uspSelectPatientByAgeResult> uspSelectPatientByAge([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Age", DbType="Int")] System.Nullable<int> age)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), age);
			return ((ISingleResult<uspSelectPatientByAgeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectPatientByFullName")]
		public ISingleResult<uspSelectPatientByFullNameResult> uspSelectPatientByFullName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientFullName", DbType="NVarChar(100)")] string patientFullName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), patientFullName);
			return ((ISingleResult<uspSelectPatientByFullNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectPatientByGender")]
		public ISingleResult<uspSelectPatientByGenderResult> uspSelectPatientByGender([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="NVarChar(50)")] string gender)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gender);
			return ((ISingleResult<uspSelectPatientByGenderResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectPatientByType")]
		public ISingleResult<uspSelectPatientByTypeResult> uspSelectPatientByType([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientType", DbType="NVarChar(50)")] string patientType)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), patientType);
			return ((ISingleResult<uspSelectPatientByTypeResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspUpdateMedicine")]
		public int uspUpdateMedicine([global::System.Data.Linq.Mapping.ParameterAttribute(Name="MID", DbType="Int")] System.Nullable<int> mID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrandName", DbType="NVarChar(100)")] string brandName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GenericName", DbType="NVarChar(MAX)")] string genericName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ExpirationDate", DbType="Date")] System.Nullable<System.DateTime> expirationDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Manufacturer", DbType="NVarChar(MAX)")] string manufacturer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Quantity", DbType="Int")] System.Nullable<int> quantity)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mID, brandName, genericName, expirationDate, manufacturer, quantity);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspUpdatePatient")]
		public int uspUpdatePatient([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PID", DbType="Int")] System.Nullable<int> pID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Age", DbType="Int")] System.Nullable<int> age, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gender", DbType="NVarChar(50)")] string gender, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Type", DbType="NVarChar(50)")] string type, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Desc", DbType="NVarChar(50)")] string desc, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Num", DbType="NChar(11)")] string num, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(MAX)")] string address)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pID, name, age, gender, type, desc, num, email, address);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.udfGetMedicineID", IsComposable=true)]
		public System.Nullable<int> udfGetMedicineID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(100)")] string name)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.udfGetPatientID", IsComposable=true)]
		public System.Nullable<int> udfGetPatientID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(100)")] string name)
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectAllEmergencyContact")]
		public ISingleResult<uspSelectAllEmergencyContactResult> uspSelectAllEmergencyContact()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspSelectAllEmergencyContactResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectAllStudentAdviser")]
		public ISingleResult<uspSelectAllStudentAdviserResult> uspSelectAllStudentAdviser()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<uspSelectAllStudentAdviserResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectPatientByFullName")]
		public ISingleResult<uspSelectPatientByFullNameResult1> uspSelectPatientByFullName1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PatientFullName", DbType="NVarChar(100)")] string patientFullName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), patientFullName);
			return ((ISingleResult<uspSelectPatientByFullNameResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectPatientByAge")]
		public ISingleResult<uspSelectPatientByAgeResult1> uspSelectPatientByAge1([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Age", DbType="Int")] System.Nullable<int> age)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), age);
			return ((ISingleResult<uspSelectPatientByAgeResult1>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectMedicineByGenericName")]
		public ISingleResult<uspSelectMedicineByGenericNameResult> uspSelectMedicineByGenericName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="GenericName", DbType="NVarChar(MAX)")] string genericName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), genericName);
			return ((ISingleResult<uspSelectMedicineByGenericNameResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.uspSelectMedicineByBrandName")]
		public ISingleResult<uspSelectMedicineByBrandNameResult> uspSelectMedicineByBrandName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="BrandName", DbType="NVarChar(100)")] string brandName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), brandName);
			return ((ISingleResult<uspSelectMedicineByBrandNameResult>)(result.ReturnValue));
		}
	}
	
	public partial class uspLoginResult
	{
		
		private int _UserID;
		
		private string _UserFullName;
		
		private string _UserType;
		
		public uspLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserFullName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string UserFullName
		{
			get
			{
				return this._UserFullName;
			}
			set
			{
				if ((this._UserFullName != value))
				{
					this._UserFullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this._UserType = value;
				}
			}
		}
	}
	
	public partial class uspSelectAllMedicineResult
	{
		
		private string _MedicineName;
		
		private string _MedicineType;
		
		private System.DateTime _MedExpDate;
		
		private string _MedManufacturer;
		
		private int _MedQTY;
		
		private string _MedStatus;
		
		private System.DateTime _MedLastUpdated;
		
		public uspSelectAllMedicineResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MedicineName
		{
			get
			{
				return this._MedicineName;
			}
			set
			{
				if ((this._MedicineName != value))
				{
					this._MedicineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineType", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MedicineType
		{
			get
			{
				return this._MedicineType;
			}
			set
			{
				if ((this._MedicineType != value))
				{
					this._MedicineType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedExpDate", DbType="Date NOT NULL")]
		public System.DateTime MedExpDate
		{
			get
			{
				return this._MedExpDate;
			}
			set
			{
				if ((this._MedExpDate != value))
				{
					this._MedExpDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedManufacturer", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MedManufacturer
		{
			get
			{
				return this._MedManufacturer;
			}
			set
			{
				if ((this._MedManufacturer != value))
				{
					this._MedManufacturer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedQTY", DbType="Int NOT NULL")]
		public int MedQTY
		{
			get
			{
				return this._MedQTY;
			}
			set
			{
				if ((this._MedQTY != value))
				{
					this._MedQTY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedStatus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MedStatus
		{
			get
			{
				return this._MedStatus;
			}
			set
			{
				if ((this._MedStatus != value))
				{
					this._MedStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedLastUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime MedLastUpdated
		{
			get
			{
				return this._MedLastUpdated;
			}
			set
			{
				if ((this._MedLastUpdated != value))
				{
					this._MedLastUpdated = value;
				}
			}
		}
	}
	
	public partial class uspSelectAllPatientResult
	{
		
		private string _PatientName;
		
		private int _PatientAge;
		
		private string _PatientGender;
		
		private string _PatientType;
		
		private string _PatientDesc;
		
		private string _PatientNum;
		
		private string _PatientEmail;
		
		private string _PatientAddress;
		
		public uspSelectAllPatientResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientName
		{
			get
			{
				return this._PatientName;
			}
			set
			{
				if ((this._PatientName != value))
				{
					this._PatientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAge", DbType="Int NOT NULL")]
		public int PatientAge
		{
			get
			{
				return this._PatientAge;
			}
			set
			{
				if ((this._PatientAge != value))
				{
					this._PatientAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientGender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientGender
		{
			get
			{
				return this._PatientGender;
			}
			set
			{
				if ((this._PatientGender != value))
				{
					this._PatientGender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientType
		{
			get
			{
				return this._PatientType;
			}
			set
			{
				if ((this._PatientType != value))
				{
					this._PatientType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientDesc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientDesc
		{
			get
			{
				return this._PatientDesc;
			}
			set
			{
				if ((this._PatientDesc != value))
				{
					this._PatientDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientNum", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string PatientNum
		{
			get
			{
				return this._PatientNum;
			}
			set
			{
				if ((this._PatientNum != value))
				{
					this._PatientNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientEmail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientEmail
		{
			get
			{
				return this._PatientEmail;
			}
			set
			{
				if ((this._PatientEmail != value))
				{
					this._PatientEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAddress", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PatientAddress
		{
			get
			{
				return this._PatientAddress;
			}
			set
			{
				if ((this._PatientAddress != value))
				{
					this._PatientAddress = value;
				}
			}
		}
	}
	
	public partial class uspSelectAllUserResult
	{
		
		private int _UserID;
		
		private string _UserFullName;
		
		private string _UserName;
		
		private string _UserPassword;
		
		private string _UserEmail;
		
		private string _UserContact;
		
		private string _UserType;
		
		public uspSelectAllUserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this._UserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserFullName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string UserFullName
		{
			get
			{
				return this._UserFullName;
			}
			set
			{
				if ((this._UserFullName != value))
				{
					this._UserFullName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserPassword", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserPassword
		{
			get
			{
				return this._UserPassword;
			}
			set
			{
				if ((this._UserPassword != value))
				{
					this._UserPassword = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserEmail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string UserEmail
		{
			get
			{
				return this._UserEmail;
			}
			set
			{
				if ((this._UserEmail != value))
				{
					this._UserEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserContact", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string UserContact
		{
			get
			{
				return this._UserContact;
			}
			set
			{
				if ((this._UserContact != value))
				{
					this._UserContact = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UserType
		{
			get
			{
				return this._UserType;
			}
			set
			{
				if ((this._UserType != value))
				{
					this._UserType = value;
				}
			}
		}
	}
	
	public partial class uspSelectMedicineByExpDateResult
	{
		
		private int _MedicineID;
		
		private string _MedicineName;
		
		private string _MedicineType;
		
		private System.DateTime _MedExpDate;
		
		private string _MedManufacturer;
		
		private int _MedQty;
		
		private string _MedStatus;
		
		private System.DateTime _MedLastUpdated;
		
		public uspSelectMedicineByExpDateResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineID", DbType="Int NOT NULL")]
		public int MedicineID
		{
			get
			{
				return this._MedicineID;
			}
			set
			{
				if ((this._MedicineID != value))
				{
					this._MedicineID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MedicineName
		{
			get
			{
				return this._MedicineName;
			}
			set
			{
				if ((this._MedicineName != value))
				{
					this._MedicineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineType", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MedicineType
		{
			get
			{
				return this._MedicineType;
			}
			set
			{
				if ((this._MedicineType != value))
				{
					this._MedicineType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedExpDate", DbType="Date NOT NULL")]
		public System.DateTime MedExpDate
		{
			get
			{
				return this._MedExpDate;
			}
			set
			{
				if ((this._MedExpDate != value))
				{
					this._MedExpDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedManufacturer", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MedManufacturer
		{
			get
			{
				return this._MedManufacturer;
			}
			set
			{
				if ((this._MedManufacturer != value))
				{
					this._MedManufacturer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedQty", DbType="Int NOT NULL")]
		public int MedQty
		{
			get
			{
				return this._MedQty;
			}
			set
			{
				if ((this._MedQty != value))
				{
					this._MedQty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedStatus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MedStatus
		{
			get
			{
				return this._MedStatus;
			}
			set
			{
				if ((this._MedStatus != value))
				{
					this._MedStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedLastUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime MedLastUpdated
		{
			get
			{
				return this._MedLastUpdated;
			}
			set
			{
				if ((this._MedLastUpdated != value))
				{
					this._MedLastUpdated = value;
				}
			}
		}
	}
	
	public partial class uspSelectMedicineByManufacturerResult
	{
		
		private int _MedicineID;
		
		private string _MedicineName;
		
		private string _MedicineType;
		
		private System.DateTime _MedExpDate;
		
		private string _MedManufacturer;
		
		private int _MedQty;
		
		private string _MedStatus;
		
		private System.DateTime _MedLastUpdated;
		
		public uspSelectMedicineByManufacturerResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineID", DbType="Int NOT NULL")]
		public int MedicineID
		{
			get
			{
				return this._MedicineID;
			}
			set
			{
				if ((this._MedicineID != value))
				{
					this._MedicineID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MedicineName
		{
			get
			{
				return this._MedicineName;
			}
			set
			{
				if ((this._MedicineName != value))
				{
					this._MedicineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineType", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MedicineType
		{
			get
			{
				return this._MedicineType;
			}
			set
			{
				if ((this._MedicineType != value))
				{
					this._MedicineType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedExpDate", DbType="Date NOT NULL")]
		public System.DateTime MedExpDate
		{
			get
			{
				return this._MedExpDate;
			}
			set
			{
				if ((this._MedExpDate != value))
				{
					this._MedExpDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedManufacturer", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MedManufacturer
		{
			get
			{
				return this._MedManufacturer;
			}
			set
			{
				if ((this._MedManufacturer != value))
				{
					this._MedManufacturer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedQty", DbType="Int NOT NULL")]
		public int MedQty
		{
			get
			{
				return this._MedQty;
			}
			set
			{
				if ((this._MedQty != value))
				{
					this._MedQty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedStatus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MedStatus
		{
			get
			{
				return this._MedStatus;
			}
			set
			{
				if ((this._MedStatus != value))
				{
					this._MedStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedLastUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime MedLastUpdated
		{
			get
			{
				return this._MedLastUpdated;
			}
			set
			{
				if ((this._MedLastUpdated != value))
				{
					this._MedLastUpdated = value;
				}
			}
		}
	}
	
	public partial class uspSelectPatientByAgeResult
	{
		
		private int _PatientID;
		
		private string _PatientName;
		
		private int _PatientAge;
		
		private string _PatientGender;
		
		private string _PatientType;
		
		private string _PatientDesc;
		
		private string _PatientNum;
		
		private string _PatientEmail;
		
		private string _PatientAddress;
		
		public uspSelectPatientByAgeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Int NOT NULL")]
		public int PatientID
		{
			get
			{
				return this._PatientID;
			}
			set
			{
				if ((this._PatientID != value))
				{
					this._PatientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientName
		{
			get
			{
				return this._PatientName;
			}
			set
			{
				if ((this._PatientName != value))
				{
					this._PatientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAge", DbType="Int NOT NULL")]
		public int PatientAge
		{
			get
			{
				return this._PatientAge;
			}
			set
			{
				if ((this._PatientAge != value))
				{
					this._PatientAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientGender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientGender
		{
			get
			{
				return this._PatientGender;
			}
			set
			{
				if ((this._PatientGender != value))
				{
					this._PatientGender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientType
		{
			get
			{
				return this._PatientType;
			}
			set
			{
				if ((this._PatientType != value))
				{
					this._PatientType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientDesc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientDesc
		{
			get
			{
				return this._PatientDesc;
			}
			set
			{
				if ((this._PatientDesc != value))
				{
					this._PatientDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientNum", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string PatientNum
		{
			get
			{
				return this._PatientNum;
			}
			set
			{
				if ((this._PatientNum != value))
				{
					this._PatientNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientEmail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientEmail
		{
			get
			{
				return this._PatientEmail;
			}
			set
			{
				if ((this._PatientEmail != value))
				{
					this._PatientEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAddress", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PatientAddress
		{
			get
			{
				return this._PatientAddress;
			}
			set
			{
				if ((this._PatientAddress != value))
				{
					this._PatientAddress = value;
				}
			}
		}
	}
	
	public partial class uspSelectPatientByFullNameResult
	{
		
		private int _PatientID;
		
		private string _PatientName;
		
		private int _PatientAge;
		
		private string _PatientGender;
		
		private string _PatientType;
		
		private string _PatientDesc;
		
		private string _PatientNum;
		
		private string _PatientEmail;
		
		private string _PatientAddress;
		
		public uspSelectPatientByFullNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Int NOT NULL")]
		public int PatientID
		{
			get
			{
				return this._PatientID;
			}
			set
			{
				if ((this._PatientID != value))
				{
					this._PatientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientName
		{
			get
			{
				return this._PatientName;
			}
			set
			{
				if ((this._PatientName != value))
				{
					this._PatientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAge", DbType="Int NOT NULL")]
		public int PatientAge
		{
			get
			{
				return this._PatientAge;
			}
			set
			{
				if ((this._PatientAge != value))
				{
					this._PatientAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientGender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientGender
		{
			get
			{
				return this._PatientGender;
			}
			set
			{
				if ((this._PatientGender != value))
				{
					this._PatientGender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientType
		{
			get
			{
				return this._PatientType;
			}
			set
			{
				if ((this._PatientType != value))
				{
					this._PatientType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientDesc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientDesc
		{
			get
			{
				return this._PatientDesc;
			}
			set
			{
				if ((this._PatientDesc != value))
				{
					this._PatientDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientNum", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string PatientNum
		{
			get
			{
				return this._PatientNum;
			}
			set
			{
				if ((this._PatientNum != value))
				{
					this._PatientNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientEmail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientEmail
		{
			get
			{
				return this._PatientEmail;
			}
			set
			{
				if ((this._PatientEmail != value))
				{
					this._PatientEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAddress", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PatientAddress
		{
			get
			{
				return this._PatientAddress;
			}
			set
			{
				if ((this._PatientAddress != value))
				{
					this._PatientAddress = value;
				}
			}
		}
	}
	
	public partial class uspSelectPatientByGenderResult
	{
		
		private int _PatientID;
		
		private string _PatientName;
		
		private int _PatientAge;
		
		private string _PatientGender;
		
		private string _PatientType;
		
		private string _PatientDesc;
		
		private string _PatientNum;
		
		private string _PatientEmail;
		
		private string _PatientAddress;
		
		public uspSelectPatientByGenderResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Int NOT NULL")]
		public int PatientID
		{
			get
			{
				return this._PatientID;
			}
			set
			{
				if ((this._PatientID != value))
				{
					this._PatientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientName
		{
			get
			{
				return this._PatientName;
			}
			set
			{
				if ((this._PatientName != value))
				{
					this._PatientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAge", DbType="Int NOT NULL")]
		public int PatientAge
		{
			get
			{
				return this._PatientAge;
			}
			set
			{
				if ((this._PatientAge != value))
				{
					this._PatientAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientGender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientGender
		{
			get
			{
				return this._PatientGender;
			}
			set
			{
				if ((this._PatientGender != value))
				{
					this._PatientGender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientType
		{
			get
			{
				return this._PatientType;
			}
			set
			{
				if ((this._PatientType != value))
				{
					this._PatientType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientDesc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientDesc
		{
			get
			{
				return this._PatientDesc;
			}
			set
			{
				if ((this._PatientDesc != value))
				{
					this._PatientDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientNum", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string PatientNum
		{
			get
			{
				return this._PatientNum;
			}
			set
			{
				if ((this._PatientNum != value))
				{
					this._PatientNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientEmail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientEmail
		{
			get
			{
				return this._PatientEmail;
			}
			set
			{
				if ((this._PatientEmail != value))
				{
					this._PatientEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAddress", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PatientAddress
		{
			get
			{
				return this._PatientAddress;
			}
			set
			{
				if ((this._PatientAddress != value))
				{
					this._PatientAddress = value;
				}
			}
		}
	}
	
	public partial class uspSelectPatientByTypeResult
	{
		
		private int _PatientID;
		
		private string _PatientName;
		
		private int _PatientAge;
		
		private string _PatientGender;
		
		private string _PatientType;
		
		private string _PatientDesc;
		
		private string _PatientNum;
		
		private string _PatientEmail;
		
		private string _PatientAddress;
		
		public uspSelectPatientByTypeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Int NOT NULL")]
		public int PatientID
		{
			get
			{
				return this._PatientID;
			}
			set
			{
				if ((this._PatientID != value))
				{
					this._PatientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientName
		{
			get
			{
				return this._PatientName;
			}
			set
			{
				if ((this._PatientName != value))
				{
					this._PatientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAge", DbType="Int NOT NULL")]
		public int PatientAge
		{
			get
			{
				return this._PatientAge;
			}
			set
			{
				if ((this._PatientAge != value))
				{
					this._PatientAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientGender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientGender
		{
			get
			{
				return this._PatientGender;
			}
			set
			{
				if ((this._PatientGender != value))
				{
					this._PatientGender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientType
		{
			get
			{
				return this._PatientType;
			}
			set
			{
				if ((this._PatientType != value))
				{
					this._PatientType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientDesc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientDesc
		{
			get
			{
				return this._PatientDesc;
			}
			set
			{
				if ((this._PatientDesc != value))
				{
					this._PatientDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientNum", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string PatientNum
		{
			get
			{
				return this._PatientNum;
			}
			set
			{
				if ((this._PatientNum != value))
				{
					this._PatientNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientEmail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientEmail
		{
			get
			{
				return this._PatientEmail;
			}
			set
			{
				if ((this._PatientEmail != value))
				{
					this._PatientEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAddress", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PatientAddress
		{
			get
			{
				return this._PatientAddress;
			}
			set
			{
				if ((this._PatientAddress != value))
				{
					this._PatientAddress = value;
				}
			}
		}
	}
	
	public partial class uspSelectAllEmergencyContactResult
	{
		
		private int _EmgyContactID;
		
		private int _PatientID;
		
		private string _EmgyRelationship;
		
		private string _EmgyContactName;
		
		private string _EmgyContactNum;
		
		private string _EmgyContactEmail;
		
		private string _EmgyContactAddress;
		
		public uspSelectAllEmergencyContactResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmgyContactID", DbType="Int NOT NULL")]
		public int EmgyContactID
		{
			get
			{
				return this._EmgyContactID;
			}
			set
			{
				if ((this._EmgyContactID != value))
				{
					this._EmgyContactID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Int NOT NULL")]
		public int PatientID
		{
			get
			{
				return this._PatientID;
			}
			set
			{
				if ((this._PatientID != value))
				{
					this._PatientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmgyRelationship", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string EmgyRelationship
		{
			get
			{
				return this._EmgyRelationship;
			}
			set
			{
				if ((this._EmgyRelationship != value))
				{
					this._EmgyRelationship = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmgyContactName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EmgyContactName
		{
			get
			{
				return this._EmgyContactName;
			}
			set
			{
				if ((this._EmgyContactName != value))
				{
					this._EmgyContactName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmgyContactNum", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string EmgyContactNum
		{
			get
			{
				return this._EmgyContactNum;
			}
			set
			{
				if ((this._EmgyContactNum != value))
				{
					this._EmgyContactNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmgyContactEmail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string EmgyContactEmail
		{
			get
			{
				return this._EmgyContactEmail;
			}
			set
			{
				if ((this._EmgyContactEmail != value))
				{
					this._EmgyContactEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmgyContactAddress", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string EmgyContactAddress
		{
			get
			{
				return this._EmgyContactAddress;
			}
			set
			{
				if ((this._EmgyContactAddress != value))
				{
					this._EmgyContactAddress = value;
				}
			}
		}
	}
	
	public partial class uspSelectAllStudentAdviserResult
	{
		
		private int _AdviserID;
		
		private int _PatientID;
		
		private string _AdviserName;
		
		private string _AdviserEmail;
		
		private string _AdviserNum;
		
		private string _AdviserDept;
		
		public uspSelectAllStudentAdviserResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdviserID", DbType="Int NOT NULL")]
		public int AdviserID
		{
			get
			{
				return this._AdviserID;
			}
			set
			{
				if ((this._AdviserID != value))
				{
					this._AdviserID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Int NOT NULL")]
		public int PatientID
		{
			get
			{
				return this._PatientID;
			}
			set
			{
				if ((this._PatientID != value))
				{
					this._PatientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdviserName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string AdviserName
		{
			get
			{
				return this._AdviserName;
			}
			set
			{
				if ((this._AdviserName != value))
				{
					this._AdviserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdviserEmail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string AdviserEmail
		{
			get
			{
				return this._AdviserEmail;
			}
			set
			{
				if ((this._AdviserEmail != value))
				{
					this._AdviserEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdviserNum", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string AdviserNum
		{
			get
			{
				return this._AdviserNum;
			}
			set
			{
				if ((this._AdviserNum != value))
				{
					this._AdviserNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdviserDept", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string AdviserDept
		{
			get
			{
				return this._AdviserDept;
			}
			set
			{
				if ((this._AdviserDept != value))
				{
					this._AdviserDept = value;
				}
			}
		}
	}
	
	public partial class uspSelectPatientByFullNameResult1
	{
		
		private int _PatientID;
		
		private string _PatientName;
		
		private int _PatientAge;
		
		private string _PatientGender;
		
		private string _PatientType;
		
		private string _PatientDesc;
		
		private string _PatientNum;
		
		private string _PatientEmail;
		
		private string _PatientAddress;
		
		public uspSelectPatientByFullNameResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Int NOT NULL")]
		public int PatientID
		{
			get
			{
				return this._PatientID;
			}
			set
			{
				if ((this._PatientID != value))
				{
					this._PatientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientName
		{
			get
			{
				return this._PatientName;
			}
			set
			{
				if ((this._PatientName != value))
				{
					this._PatientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAge", DbType="Int NOT NULL")]
		public int PatientAge
		{
			get
			{
				return this._PatientAge;
			}
			set
			{
				if ((this._PatientAge != value))
				{
					this._PatientAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientGender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientGender
		{
			get
			{
				return this._PatientGender;
			}
			set
			{
				if ((this._PatientGender != value))
				{
					this._PatientGender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientType
		{
			get
			{
				return this._PatientType;
			}
			set
			{
				if ((this._PatientType != value))
				{
					this._PatientType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientDesc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientDesc
		{
			get
			{
				return this._PatientDesc;
			}
			set
			{
				if ((this._PatientDesc != value))
				{
					this._PatientDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientNum", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string PatientNum
		{
			get
			{
				return this._PatientNum;
			}
			set
			{
				if ((this._PatientNum != value))
				{
					this._PatientNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientEmail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientEmail
		{
			get
			{
				return this._PatientEmail;
			}
			set
			{
				if ((this._PatientEmail != value))
				{
					this._PatientEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAddress", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PatientAddress
		{
			get
			{
				return this._PatientAddress;
			}
			set
			{
				if ((this._PatientAddress != value))
				{
					this._PatientAddress = value;
				}
			}
		}
	}
	
	public partial class uspSelectPatientByAgeResult1
	{
		
		private int _PatientID;
		
		private string _PatientName;
		
		private int _PatientAge;
		
		private string _PatientGender;
		
		private string _PatientType;
		
		private string _PatientDesc;
		
		private string _PatientNum;
		
		private string _PatientEmail;
		
		private string _PatientAddress;
		
		public uspSelectPatientByAgeResult1()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientID", DbType="Int NOT NULL")]
		public int PatientID
		{
			get
			{
				return this._PatientID;
			}
			set
			{
				if ((this._PatientID != value))
				{
					this._PatientID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientName
		{
			get
			{
				return this._PatientName;
			}
			set
			{
				if ((this._PatientName != value))
				{
					this._PatientName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAge", DbType="Int NOT NULL")]
		public int PatientAge
		{
			get
			{
				return this._PatientAge;
			}
			set
			{
				if ((this._PatientAge != value))
				{
					this._PatientAge = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientGender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientGender
		{
			get
			{
				return this._PatientGender;
			}
			set
			{
				if ((this._PatientGender != value))
				{
					this._PatientGender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientType", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientType
		{
			get
			{
				return this._PatientType;
			}
			set
			{
				if ((this._PatientType != value))
				{
					this._PatientType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientDesc", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PatientDesc
		{
			get
			{
				return this._PatientDesc;
			}
			set
			{
				if ((this._PatientDesc != value))
				{
					this._PatientDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientNum", DbType="NChar(11) NOT NULL", CanBeNull=false)]
		public string PatientNum
		{
			get
			{
				return this._PatientNum;
			}
			set
			{
				if ((this._PatientNum != value))
				{
					this._PatientNum = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientEmail", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PatientEmail
		{
			get
			{
				return this._PatientEmail;
			}
			set
			{
				if ((this._PatientEmail != value))
				{
					this._PatientEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PatientAddress", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string PatientAddress
		{
			get
			{
				return this._PatientAddress;
			}
			set
			{
				if ((this._PatientAddress != value))
				{
					this._PatientAddress = value;
				}
			}
		}
	}
	
	public partial class uspSelectMedicineByGenericNameResult
	{
		
		private int _MedicineID;
		
		private string _MedicineName;
		
		private string _MedicineType;
		
		private System.DateTime _MedExpDate;
		
		private string _MedManufacturer;
		
		private int _MedQty;
		
		private string _MedStatus;
		
		private System.DateTime _MedLastUpdated;
		
		public uspSelectMedicineByGenericNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineID", DbType="Int NOT NULL")]
		public int MedicineID
		{
			get
			{
				return this._MedicineID;
			}
			set
			{
				if ((this._MedicineID != value))
				{
					this._MedicineID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MedicineName
		{
			get
			{
				return this._MedicineName;
			}
			set
			{
				if ((this._MedicineName != value))
				{
					this._MedicineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineType", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MedicineType
		{
			get
			{
				return this._MedicineType;
			}
			set
			{
				if ((this._MedicineType != value))
				{
					this._MedicineType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedExpDate", DbType="Date NOT NULL")]
		public System.DateTime MedExpDate
		{
			get
			{
				return this._MedExpDate;
			}
			set
			{
				if ((this._MedExpDate != value))
				{
					this._MedExpDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedManufacturer", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MedManufacturer
		{
			get
			{
				return this._MedManufacturer;
			}
			set
			{
				if ((this._MedManufacturer != value))
				{
					this._MedManufacturer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedQty", DbType="Int NOT NULL")]
		public int MedQty
		{
			get
			{
				return this._MedQty;
			}
			set
			{
				if ((this._MedQty != value))
				{
					this._MedQty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedStatus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MedStatus
		{
			get
			{
				return this._MedStatus;
			}
			set
			{
				if ((this._MedStatus != value))
				{
					this._MedStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedLastUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime MedLastUpdated
		{
			get
			{
				return this._MedLastUpdated;
			}
			set
			{
				if ((this._MedLastUpdated != value))
				{
					this._MedLastUpdated = value;
				}
			}
		}
	}
	
	public partial class uspSelectMedicineByBrandNameResult
	{
		
		private int _MedicineID;
		
		private string _MedicineName;
		
		private string _MedicineType;
		
		private System.DateTime _MedExpDate;
		
		private string _MedManufacturer;
		
		private int _MedQty;
		
		private string _MedStatus;
		
		private System.DateTime _MedLastUpdated;
		
		public uspSelectMedicineByBrandNameResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineID", DbType="Int NOT NULL")]
		public int MedicineID
		{
			get
			{
				return this._MedicineID;
			}
			set
			{
				if ((this._MedicineID != value))
				{
					this._MedicineID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MedicineName
		{
			get
			{
				return this._MedicineName;
			}
			set
			{
				if ((this._MedicineName != value))
				{
					this._MedicineName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedicineType", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MedicineType
		{
			get
			{
				return this._MedicineType;
			}
			set
			{
				if ((this._MedicineType != value))
				{
					this._MedicineType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedExpDate", DbType="Date NOT NULL")]
		public System.DateTime MedExpDate
		{
			get
			{
				return this._MedExpDate;
			}
			set
			{
				if ((this._MedExpDate != value))
				{
					this._MedExpDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedManufacturer", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MedManufacturer
		{
			get
			{
				return this._MedManufacturer;
			}
			set
			{
				if ((this._MedManufacturer != value))
				{
					this._MedManufacturer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedQty", DbType="Int NOT NULL")]
		public int MedQty
		{
			get
			{
				return this._MedQty;
			}
			set
			{
				if ((this._MedQty != value))
				{
					this._MedQty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedStatus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MedStatus
		{
			get
			{
				return this._MedStatus;
			}
			set
			{
				if ((this._MedStatus != value))
				{
					this._MedStatus = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedLastUpdated", DbType="DateTime NOT NULL")]
		public System.DateTime MedLastUpdated
		{
			get
			{
				return this._MedLastUpdated;
			}
			set
			{
				if ((this._MedLastUpdated != value))
				{
					this._MedLastUpdated = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
